@../../Schemas/DW/Tables/build_all.sql
@../../Schemas/DW/Sequences/build_all.sql
@../../Schemas/DW/Views/build_all.sql
@../../Schemas/DW/MaterializedViews/build_all.sql
@../../Schemas/DW/Functions/build_all.sql
@../../Schemas/DW/Procedures/build_all.sql
@../../Schemas/DW/Packages/build_all.sql
@../../Schemas/DW/Constraints/build_all.sql
@../../Schemas/DW/StaticData/build_all.sql
