@../../Schemas/ARCH/Tables/build_all.sql
@../../Schemas/ARCH/Sequences/build_all.sql
@../../Schemas/ARCH/Views/build_all.sql
@../../Schemas/ARCH/MaterializedViews/build_all.sql
@../../Schemas/ARCH/Functions/build_all.sql
@../../Schemas/ARCH/Procedures/build_all.sql
@../../Schemas/ARCH/Packages/build_all.sql
@../../Schemas/ARCH/Constraints/build_all.sql
@../../Schemas/ARCH/StaticData/build_all.sql
