@../../Schemas/DM/Tables/build_all.sql
@../../Schemas/DM/Sequences/build_all.sql
@../../Schemas/DM/Views/build_all.sql
@../../Schemas/DM/Functions/build_all.sql
@../../Schemas/DM/Procedures/build_all.sql
@../../Schemas/DM/Packages/build_all.sql
@../../Schemas/DM/Constraints/build_all.sql
@../../Schemas/DM/StaticData/build_all.sql
@../../Schemas/DM/MaterializedViews/build_all.sql
@../../Schemas/DM/Tables/build_all.sql
@../../Schemas/DM/Sequences/build_all.sql
@../../Schemas/DM/Views/build_all.sql
@../../Schemas/DM/Functions/build_all.sql
@../../Schemas/DM/Procedures/build_all.sql
@../../Schemas/DM/Packages/build_all.sql
@../../Schemas/DM/Constraints/build_all.sql
@../../Schemas/DM/StaticData/build_all.sql
@../../Schemas/DM/MaterializedViews/build_all.sql
