@../../Schemas/REF/Tables/build_all.sql
@../../Schemas/REF/Sequences/build_all.sql
@../../Schemas/REF/Views/build_all.sql
@../../Schemas/REF/MaterializedViews/build_all.sql
@../../Schemas/REF/Functions/build_all.sql
@../../Schemas/REF/Procedures/build_all.sql
@../../Schemas/REF/Packages/build_all.sql
@../../Schemas/REF/Constraints/build_all.sql
@../../Schemas/REF/StaticData/build_all.sql
