@../../Schemas/STAGE/Tables/build_all.sql
@../../Schemas/STAGE/Sequences/build_all.sql
@../../Schemas/STAGE/Views/build_all.sql
@../../Schemas/STAGE/MaterializedViews/build_all.sql
@../../Schemas/STAGE/Functions/build_all.sql
@../../Schemas/STAGE/Procedures/build_all.sql
@../../Schemas/STAGE/Packages/build_all.sql
@../../Schemas/STAGE/Constraints/build_all.sql
@../../Schemas/STAGE/StaticData/build_all.sql
